#!/usr/bin/env bash
if [ -z "$DB_USER" ] || [ -z "$DB_NAME" ]; then
  echo "You must have your environment configured for the database"
  echo "example:"
  echo "  export DB_NAME=badgekitapi"
  echo "  export DB_USER=root"
  echo "  export DB_PASSWORD=mypassword"
else
  if [ -z "$DB_PASSWORD" ]; then
    mysql -u $DB_USER $DB_NAME < schema.sql
  else
    mysql -u $DB_USER "-p$DB_PASSWORD" $DB_NAME < schema.sql
  fi
fi
